# Generated by Django 4.1.13 on 2024-04-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254)),
                ('domain', models.CharField(max_length=100)),
                ('num_questions', models.IntegerField()),
                ('time_taken', models.DateTimeField()),
                ('question', models.TextField()),
                ('user_answer', models.TextField()),
                ('expected_answer', models.TextField()),
                ('video_analysis_results', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
